<?php
namespace Sync\Entities;

class IntegrationEntity
{
    const INTEGRATION_TYPE_NONE = 0;
    const INTEGRATION_TYPE_GOOGLE = 1;
    const INTEGRATION_TYPE_CLEVER = 2;
    const INTEGRATION_TYPE_CLASSLINK = 3;
    const INTEGRATION_TYPE_GG4L = 4;
    const INTEGRATION_TYPE_CLEVER_CLASSROOM = 5;
    const INTEGRATION_TYPE_MICROSOFT = 6;
    const INTEGRATION_TYPE_BLACKBOARD = 7;
    const INTEGRATION_TYPE_CANVAS = 8;
}
